### ISSUE TITLE
CollectionView scrolls to top when I open the drawer

### ISSUE THREAD

**Issue by cosmicsalad** [mkko/DrawerView#5] opened 2019-03-26 22:18 UTC
So I'm using the drawer as a "Settings" view, and it is pulled up over a CollectionView. When I open the Settings drawer, if I had scrolled at all in the CollectionView beforehand, it scrolls it back to the top. Any way to fix this?

**Comment by mkko** [comment] 2019-03-27 10:04
Hi. This definitely sounds like a bug and ought to be fixed.

So you mean that if drawer is displayed on top of a collection view (or any scroll view?), the scroll view under the drawer scrolls back to the top because of the drawer being displayed? As far as I know, the drawer shouldn't intervene anything outside its subviews. Any chance you'd have a reproducible example project for this?

**Comment by mkko** [comment] 2021-02-26 10:53
Please, let me know if this issue is still valid. I'm closing this for now.

**Closed as completed by mkko** 2021-02-26 10:53 UTC
